apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: my-jaeger
spec:
  agent:
    strategy: DaemonSet
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  labels:
    app: observability
spec:
  ports:
    - protocol: "TCP"
      port: 16686
      targetPort: 16686
  selector:
    app: my-jaeger-collector
  type: LoadBalancer